### ISSUE TITLE
Flex2: cannot execute binary file

### ISSUE THREAD

**Issue by xxmadbrinexx** [kirjavascript/Flex2#12]
So I'm trying to make a Sonic 2 ROM Hack, and I found that Flex 2 would be a good tool for graphics hacking. I'm using Ubuntu 18.04 LTS 64-bit. When I try to run the Flex2 executable, it gives me this error: 
`Flex2: Flex2: cannot execute binary file`
Am I doing something wrong?

**Comment by lilggamegenius** [comment]
Which release did you download?

**Comment by xxmadbrinexx** [comment]
bugfix release 0.0.6 flex2-linux-x64.tar.gz, the newest release

**Comment by kirjavascript** [comment]
I'm not sure what that would happen

you could try compiling it from source to see if it's an architecture issue?

**Comment by kirjavascript** [comment]
try the latest release, if it's still a problem open a new issue
