### ISSUE TITLE
Tutorial on how to use?

### ISSUE THREAD

**Issue by zumpchke** [kirjavascript/Flex2#14]
I want to use this to make a ROM hack to modify a sprite (say, of Sonic standing). How do I go about this? There doesn't seem to be any documentation.

**Comment by GabrielRavier** [comment]
Someone should make an issue for adding documentation and ref this

**Comment by kirjavascript** [comment]
Hi.

There is documentation available in the program already that is in the 'documentation' tab. This is the same information available in the README.md of this project.

I aimed to only include what was needed and that couldn't be found from playing with the UI.

This is just a tool for editing mapping and sprite resources, perhaps a full tutorial for doing a ROM hack is out of scope?

**Comment by Hitaxas** [comment]
I did have some people ask me about how to use the program. So here is a short video I made explaining how to load files into it. 
https://youtu.be/u4X_G95mzZs

**Comment by Pug172cm** [comment]
Can someone tell me how to actually download this hack and open it because I am at opening stuff on my PC.
