### ISSUE TITLE
Frame Remapping

### ISSUE THREAD

**Issue by LuigiXHero** [kirjavascript/Flex2#19]
Doesn't seem like this is still being worked on but might as well bring this up.
Remapping frames is pretty tedious in this program atm, You have to click and drag sprites which is fine and all but it's really hard to do it when the destination you want is far away. Like for instance Sonic's standing frame is 1 and if you import a new sprite it'll put it down at the bottom, let's say $84. You then have to drag it up super slowly but holding it on the top of the screen or try the page up buttons which only works like once or twice before you have to set the frame down and try again.

My suggestion is to have a box that has the frame number in it and you can type what you want it to be. If you go over max either have it cap off or create empty frames. (could even ask you)

**Comment by LuigiXHero** [comment]
Thinking about this a bit more: Said box would be great in the raw mapping editor, But having a keyboard shortcut for just moving a frame over by one like SonMapED would be nice also.
You already have [] switch between selecting sprites and holding shift to jump by 8. So holding Ctrl+[] would work.

**Comment by kirjavascript** [comment]
Hi, sorry about the apparent inactivity. I have recently started working on a new version of the editor with new features. Will look at this in the process.

Adding a new keyboard shortcut sounds like a good way of achieving this.

**Comment by LuigiXHero** [comment]
Yeah i've been doing that and a full screen option for tabs would be nice

**Comment by kirjavascript** [comment]
I've added ctrl+] and ctrl+[ as keyboard shortcuts to swap sprites. So you could type something like `48 ctrl+]`
 to move a sprite 48 places to the right.

Also added a fullscreen option for tabs.

these are in version 0.0.7 that is releasing in the next few days
