### ISSUE TITLE
Sonic 2: Sonic/Tails Special Stage DPLC Mappings Support

### ISSUE THREAD

**Issue by Alriightyman** [kirjavascript/Flex2#21]
Apparently, the Sonic/Tails Special Stage dplc mappings are in a different format than the normal mappings.

Link: http://info.sonicretro.org/SCHG_How-to:Change_the_Special_Stage_characters_to_use_normal_DPLCs

**Comment by kirjavascript** [comment]
after version 0.0.7 is released the next feature on the roadmap is fully customizable mappings, I'll include definition files for this format

**Comment by kirjavascript** [comment]
added, will be available in the next release
