### ISSUE TITLE
KosM art cannot be loaded in v0.0.7

### ISSUE THREAD

**Issue by Chainspike** [kirjavascript/Flex2#24]
There seems to be an issue when trying to load KosM art in the latest release. Nothing appears to get loaded. Nemesis and uncompressed work fine, so it's probably an issue with the decompressor? This problem didn't occur in v0.0.6. I'm running Windows 7 (64-bit) and the issue persists with both the x86 and x64 releases of Flex2. Below is an image of what it looks like:
![Flex2](https://user-images.githubusercontent.com/49379647/91932745-06783b80-ecb5-11ea-9b37-5d6571d2c68c.png)

**Comment by kirjavascript** [comment]
Thanks for the bug report

This is on me for not testing this format when porting over the new compressors. Looking into it now and have a vague idea of the problem. 

Will make a new release once it's fixed.

**Comment by kirjavascript** [comment]
fixed in 95c9acdb451757d47ecd0053bcdf34f37f7e61e0

releasing 0.0.8 now...
