### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by flamewing** [kirjavascript/Flex2#26]
Creating a new project for trying flex2, I encountered a few issues with regards to usability. The most glaring ones:

- There should be a way to configure per-project defaults for mapping/DPLC format. Currently, there is a lot of clicking needed to create more than one object in the UI. This works double for custom mapping/DPLC formats, maybe there should be a way to create them on a project basis with a name and they appear on the drop down list of formats.
- There should be a way to specify per-project path defaults for the various data files. For example, in S2 disassembly you could set 'art/palettes' for palettes, 'mappings/sprite' for mappings, and 'mappings/spriteDPLC' for DPLC, and maybe 'art/uncompressed' for uncompressed art, etc. Whenever you click to load a given piece of data, the corresponding path would start selected.
- There should be a way to reorder objects in a project, be it by drag/drop or by buttons to move up/down.
- Likewise, there should be a way to delete objects from a project.
- Another possibility would be to duplicate an object.
- Mapping mode prevents you from actually seeing the sprite pieces if the window is not big enough. Maybe the floating menu should be rethought.
- Enabling raw editor without memorizing the hotkey to disable it can force a restart of flex to close it. There should be a close button available.
- There should be a way to zoom out the images on the 'sprites' strip on the right. Especially for larger sprites, they can overflow the size available for each frame, but also being able to see more frames would be good.
- A goto frame functionality might be useful.

If you prefer, I can break this up into multiple issues.

**Comment by flamewing** [comment]
Another one: there should be a way to specify skipping palette lines from a palette file.

**Comment by kirjavascript** [comment]
These are good suggestions. A single issue is a good place to collect the various related problems.

Projects themselves can get quite unwieldy. Along the same lines, once the File Menu works there should be a 'copy to project' option. 

Changing the file input component to let you edit the path after you have added a file would be useful too.

There is a button for deleting, but you have to expand the config to open it. 

For goto frame you can type `<13]` to go to the thirteenth frame, for example. But I suppose not everyone likes keyboard commands.

**Comment by kirjavascript** [comment]
Most of these things have now been address in version 1.0.0

Create a new issue if there are still problems, cheers!
