### ISSUE TITLE
You may have a memory leak

### ISSUE THREAD

**Issue by JoenickROS** [kirjavascript/Flex2#27]
When you start Flex2 it is on average using around 300mb of memory, well I've noticed that after a while (30 minutes or so) that it sometimes spikes to 1500mb (when editing mappings) or decreased to as low as 14mb (when in drawing mode). If it helps I can send you the files I'm working with so you can see if you get a similar result.

**Comment by kirjavascript** [comment]
Hi, I played around and couldn't replicate this. It may be an operating system specific problem which will be harder to test. What OS / specs do you have.

If the RAM usage decreases again I dont think it's a memory leak, just memory intensive processing in certain parts (editing mappings) which can be improved. Additionally, processes can sometimes keep hold of memory they're not using unless requested by the OS, which may contribute to the weirdness. It's hard to figure out if/what is the problem.

You can send the files for me to try and see if anything is weird though.
