### ISSUE TITLE
Main window is not resizable or closable on Linux

### ISSUE THREAD

**Issue by vladikcomper** [kirjavascript/Flex2#28]
As of version 0.0.8, Flex 2 has various usability issues, at least when run under Linux.

The main window has no close/maximize/minimize controls and is not resizable, as seen on the screenshot below:

![Main window](https://vladikcomper.scanf.su/public/misc/img/flex2_windowissue.png)

Moreover, the window doesn't even appear on the task bar, so it's hard to find when it's masked by other windows.
What's worse, since window doesn't enable closing, there's no way to normally quit Flex 2 other than manually killing its process.
Improper termination of the application, in turn, soon leads to even worse side effects, like Flex 2 unable to load at all on the next launch (all I see is empty window with the background), until application data (including local storage) is cleared manually.

This makes Flex 2 almost unusable on Linux.
I'm currently running it on Ubuntu 18.04-based distro.

**Comment by kirjavascript** [comment]
Hey thanks for the report.

I run Flex2 on linux - but I'm using a tiling window manager so it is not affected by issues like this.

Here's a version that may fix the issue: https://easyupload.io/phb7as

Let me know if it's working now and I can do a new release. Also let me know if this resolves the issue with having to clear local storage.

**Comment by vladikcomper** [comment]
The new version worked like a charm, thank you!

Every issue I mentioned seems to be fixed. 

As for the local storage problem, I cannot reproduce it so far. 
Unfortunately, I couldn't collect any meaningful info on the problem, since the application didn't display any error messages or saved logs I could review.

I attempted to deploy a dev version from the sources, but I had multiple issues with getting it to work at all (I'm no Electron or JavaScript developer to begin with).
It crashed with syntax error in **app/components/ui/select/index.js** in the following line:

```js
const value = this.options.find((d) => d.value == store[accessor])?.label;
```
I'm not familiar with this syntax, but I believed, this would've been the working substitute:

```js
const value = this.options.find((d) => d.value == store[accessor]) && this.options.find((d) => d.value == store[accessor]).label;
```

After fixing this file, the application crashed with some sort of "duplicate element ID" error in a model.
I'm not sure, if this is related to the local storage issue or not.

I've installed NodeJS v.12, but it appears it doesn't support some of the syntax sugar you're using. If a newer version is required, I think it should be referred to in a `package.json` file (I'm no expert, but I've seen some npm packages require a certain minimal version of NodeJS).

**Comment by kirjavascript** [comment]
So instead of putting out a new release I just updated the v0.0.8 archive for linux, glad it's resolved.

The other bug I have seen myself, but thought it only happened in development. It's known and will fix it, but if it doesnt appear to be happening for you now that's great.

As for the node versioning, yeah that syntax requires a newer version, but since electron bundles the node version required it shouldn't impact users ever. For development, yeah it does make sense to list which engine is required though so I will add it. Thanks for looking!
