### ISSUE TITLE
Mappings Are Blank

### ISSUE THREAD

**Issue by AlexField442** [kirjavascript/Flex2#33]
Okay, I'm not sure why, but this issue is happening; I am making a Sonic 1 hack but for some reason all of Sonic's mappings are blank; these are my settings. Why is this happening?
![Flex 2 9_04_2021 2_26_39 PM](https://user-images.githubusercontent.com/62088798/114128393-9b27d380-993f-11eb-8101-f25198723a57.png)

**Comment by kirjavascript** [comment]
which disassembly is this?

**Comment by AlexField442** [comment]
Hivebrain 2005 (AS edition)

**Comment by AlexField442** [comment]
Wait, I fixed it! Turns out you NEED to have an ASM label, even though this would only be necassary for Sonic 3K.

**Comment by kirjavascript** [comment]
I change this in version 1.1.2 where it can open these types of mappings without having to edit them first
