### ISSUE TITLE
Pressing the "autoarrange tiles" button seems to always *add* tiles

### ISSUE THREAD

**Issue by GeminiCrafterMan** [kirjavascript/Flex2#37]
![image](https://user-images.githubusercontent.com/8532523/116577479-7f7c7100-a8de-11eb-957f-3153003a7e6b.png)
Press the button...
![image](https://user-images.githubusercontent.com/8532523/116577509-86a37f00-a8de-11eb-974f-fbb840379b28.png)

**Comment by kirjavascript** [comment]
It's not always possible to easily autoarrange tiles without adding new ones, because of the way the mappings are arranged

it might be possible to improve or provide an alternative though
