### ISSUE TITLE
Mappings dont works with S1 Github disasm

### ISSUE THREAD

**Issue by DarkexSS** [kirjavascript/Flex2#38]
I make a sprite edit in Sonic 1, i saved the mappings and at the moment to compile shows errors in the mappings
If you wanna see the error i adjunt the Errors.txt
[errors.txt](https://github.com/kirjavascript/Flex2/files/6586114/errors.txt)

**Comment by kirjavascript** [comment]
You need to change the label to `Map_Sonic_internal` in the UI
