### ISSUE TITLE
Sort Sprite Sheet into Rows

### ISSUE THREAD

**Issue by MainMemory** [kirjavascript/Flex2#4]
It would be convenient to have imported sprites organized into rows and sorted by their position within the rows, [as SpritePlotter.NET does](https://github.com/sonicretro/SonLVL/blob/master/SpritePlotter.NET/Program.cs#L241-L254).

**Comment by kirjavascript** [comment]
had to do it differently [0e83387](https://github.com/kirjavascript/Flex2/commit/0e8338779ced42942f46734fd740e4106cb60a8b#diff-ee72a7d781fd8190c81e7f2fba14a563L24)

not sure if this warrants a seperate release

**Comment by MainMemory** [comment]
Well, as long as it works similarly, that's fine.
