### ISSUE TITLE
Where do I load the ROM file?

### ISSUE THREAD

**Issue by ShadowMan44** [kirjavascript/Flex2#43]
Yeah uh this tool looks really amazing, but where do I open an actual rom file? There's no actual guide on how you edit the in-game's sprites anywhere. I'm practically left in the dark here!

**Comment by kirjavascript** [comment]
Hi there!

This project doesnt work with ROM files, you need to use a disassembly like the one here; [](https://github.com/sonicretro/s1disasm)

Once you have a split disassembly up and running, you need to select the art, mappings and palette files from the sprite you want to edit in the project view. Then you can edit it, save, and rebuild the disassembly.

**Comment by ShadowMan44** [comment]
How the hell do I disassemble a rom? All I wanted to do was edit Sonic's sprites without having limitations like crappy old SonikSprite does.

**Comment by kirjavascript** [comment]
here are some links;
http://info.sonicretro.org/SCHG_How-to:Set_up_a_Sonic_1_split_disassembly
http://info.sonicretro.org/Disassemblies
https://segaretro.org/Disassembly
