### ISSUE TITLE
Uneven scaling of sprites

### ISSUE THREAD

**Issue by flamewing** [kirjavascript/Flex2#45]
The sprite strip on the left side uses a different scaling value for each sprite frame. There should be an option to have them all use the same scale, and maybe it should be on by default. As is, it makes it difficult to judge if the sprites are of the appropriate size.

**Comment by kirjavascript** [comment]
note to self: instead of choosing a different scaling for each sprite, choose whichever keeps most (all?) of the sprites within frame
also add a slider component to change the zoom 

this is the autodismiss behaviour all over again

**Comment by kirjavascript** [comment]
fixed in 131c83abb978116514c8a504f08e0bfae7b829c8
