### ISSUE TITLE
Keep getting "Error: Can only save art at offset 0" despite it being set on 0

### ISSUE THREAD

**Issue by TheRealBlueStar** [kirjavascript/Flex2#49]
I've only encountered this recently and I asked around the Sonic Retro Discord server looking for help with this bug, but whenever I edit a piece of art using offsets, mappings, dplcs and palletes, I try to save my work and I keep getting this message. I'm working with a Sonic 1 dissassembly and no matter what I edit from the disasm, I keep constantly getting the same issue. Is there any fix for this?
![image](https://user-images.githubusercontent.com/103774141/163605790-6c4f8a30-113f-46d4-a058-448a1ee05813.png)

**Comment by kirjavascript** [comment]
can you try entirely clearing the contents of the offset box try saving again

**Comment by TheRealBlueStar** [comment]
> can you try entirely clearing the contents of the offset box try saving again

i did as you said and im still getting the same error

**Comment by TheRealBlueStar** [comment]
> can you try entirely clearing the contents of the offset box try saving again

my bad, it worked now. thank you
