### ISSUE TITLE
Mappings appear to occasionally corrupt when opening Sonic CD format graphics

### ISSUE THREAD

**Issue by ghbbeep** [kirjavascript/Flex2#51]
Using Ralakimus' disassembly, I opened all the files required, and the sprites will either:

-Work fine
-Take parts of themselves and mash them into one sprite
-Slice themselves apart and rearrange themselves slightly

**Comment by kirjavascript** [comment]
Is there a specific example that does this consistently? or is it random?

I opened the sonic and signpost art from the disassembly and that seems to work okay

**Comment by ghbbeep** [comment]
As it turns out, i'm blind and I set the offset to 1 by accident. Oops!
