### ISSUE TITLE
Option for DPLCs beyond 16 tiles

### ISSUE THREAD

**Issue by RealMalachi** [kirjavascript/Flex2#55]
Basically, if you make a DPLC format compatible with tiles counts beyond 16, Flex2 won't magically let you go beyond that
If you manually make the DPLCs go beyond 16 tiles, Flex2 will recognize and render that, but if you try to increment or decrement the number of tiles on the tool, it'll snap back to 16

Here's a demonstration with the shield. Tested with 1.1.4, though I doubt the recent versions have a fix for this yet
https://youtu.be/ofXgLsiUmHs

**Comment by kirjavascript** [comment]
should be fixed in: https://github.com/kirjavascript/Flex2/commit/9b7f29e79ce5b53e8880cc8b4325575a625fba2c

will be in the next release but I dont know when that'll be. do you want a copy of a fixed build in the meantime?

**Comment by RealMalachi** [comment]
In all honesty, I just found it interesting that it even rendered beyond 16 tiles
And yeah, a fixed build would be nice

**Comment by kirjavascript** [comment]
https://send.zcyph.cc/download/b421227b9bd4853f/#ExVBdOb47qla9y-dJgSb7g
