### ISSUE TITLE
Custom Mapping Format - Support for Macros?

### ISSUE THREAD

**Issue by VAdaPEGA** [kirjavascript/Flex2#56]
Rather than having to change formats for every single thing between projects, I'd like to have a macro for one format so mappings can be exchanged between games without the need to convert them from game to game (and to allow for changing bhow the game reads mapping formats without having to reconvert all sprite mappings)

![image](https://user-images.githubusercontent.com/50675500/221383168-20dbf749-85cf-4a7f-b507-f8670f2835a0.png)

![image](https://user-images.githubusercontent.com/50675500/221383232-7aa992a0-90a6-45d3-8f79-158ef7a4f3eb.png)

I had something of the sorts in "I made you a Salad" for the HUD object since I needed to change the RING text to STEAK, ignore the VRAM part, that was a mess
But a system like this would work really well with Flex2 as an option if possible, with support for renaming the macro as well as offset table macros

![image](https://user-images.githubusercontent.com/50675500/221383357-16c99436-0dfd-4df4-b43f-0be6cac2cd20.png)

Here's a mockup of what could be done

**Comment by kirjavascript** [comment]
Hi there! These are good ideas

Stronger custom mappings is something I want to do next with this project, but it's going to require a bit of a refactor.

Currently the base format for everything is binary, and more advanced asm (especially for output) will take some work to achieve to get good support.

There's a balance to be found between making it nice for users and actually making it implementable, as macro support could get very complex.

I can update here as I make progress though.

**Comment by kirjavascript** [comment]
This is now possible in 1.3.0

and example with `MapMacros.asm` has been provided
