### ISSUE TITLE
Please update Electron version for better Wayland support

### ISSUE THREAD

**Issue by kuroya2mouse** [kirjavascript/Flex2#57]
![изображение](https://user-images.githubusercontent.com/108447847/222727123-6902d56e-13fa-4ad7-980b-9159347fd6bd.png)

(electron 23 runtime)

Please update Flex 2 to newer electron version. Old versions have bad ozone-platform=wayland support

**Comment by kirjavascript** [comment]
the current dev branch should be using the latest electron if you want to try that

**Comment by kuroya2mouse** [comment]
i use script in development/build.sh
and flex 2 don't working... did I do something wrong?

![NWAY](https://github.com/kirjavascript/Flex2/assets/108447847/15ef4032-522c-424f-ac5b-64c2a0b367a4)

**Comment by kirjavascript** [comment]
you need to build frontend assets

run `yarn` then `yarn start`

**Comment by kirjavascript** [comment]
version 1.3.0 is using the latest version of electron
