### ISSUE TITLE
How do I edit the title emblem (the foreground on the title screen)?

### ISSUE THREAD

**Issue by hello10293** [kirjavascript/Flex2#59]
I'm using the Sonic 1 Split and Text decompilation by Hivebrain. I got the color palette and the art working, but I couldn't get the mappings to work. In the sprites panel, you only see a lot of [BLANK] sprites. Is there some setting I have to turn on?

![image](https://github.com/kirjavascript/Flex2/assets/54760280/ca0faa5c-c94c-45c0-88f5-7fe8612378e0)

**Comment by TheWindowsPro98** [comment]
The title screen emblem is actually displayed on one of the background layers; it's not a sprite and therefore won't show up in Flex.

**Comment by kirjavascript** [comment]
Flex2 doesnt support background mappings, just sprite mappings

I'm not against adding it in future though

**Comment by hello10293** [comment]
> Flex2 doesnt support background mappings, just sprite mappings
> 
> I'm not against adding it in future though

I didn't know this before. After the post I made, I decided to edit the tiles manually using fatilety, but thanks for bringing this up :).
