### ISSUE TITLE
Saving data without loading it destroys files

### ISSUE THREAD

**Issue by Leo40Git** [kirjavascript/Flex2#6]
Hitting "Save Data" before "Load Data" changes all files to be 0 bytes. Seems like there should be something preventing that...

**Comment by kirjavascript** [comment]
Well, that's desired behaviour. You're saving whatever you have loaded to the configuration. If done in mistake, you should be able to easily revert with version control (you have version control, right?)

It's possible that I can ask the user if they really want to save 0 byte files - but there are other cases like clicking on the wrong save button that will lose some of your data - and it's not possible to defend against something like this.

**Comment by Leo40Git** [comment]
Yeah I have version control, I also haven't actually changed anything yet art-wise. So no damage done!
A warning for that would probably be a good idea.

**Comment by kirjavascript** [comment]
k. leaving this open until I decide what to do with it

**Comment by kirjavascript** [comment]
project UI rewritten, might be harder to make this mistake now

will be out in 1.0.0
