### ISSUE TITLE
sprites are not loading??

### ISSUE THREAD

**Issue by PuzzlingGGG** [kirjavascript/Flex2#60]
ive tried every tutorial yet they do not work, i am using [this repository](https://github.com/sonicretro/s2disasm) with a flex 2 file already in it, but when i press object...
nothing.
no sprites, nothing in the "mappings"
super confused as i've never used this program before

**Comment by FourHawk** [comment]
This appears to be an issue with the Sonic 1 Disassembly as well, The mapping aren't loading for that, the Sonic and Knuckles Disassembly works however KIS2 doesn't work, i've double and triple checked that i loaded the correct files and still no mappings, strange.

**Comment by kirjavascript** [comment]
I'll try and find some time to test this soon

**Comment by kirjavascript** [comment]
ah this needs macro support. I will attempt to implement it

**Comment by FourHawk** [comment]
Ah, that makes sense now that i think about it, well glad to know it was an issue that needed addressing

**Comment by rocko2314243** [comment]
Why has no one talked about this

**Comment by kirjavascript** [comment]
> Why has no one talked about this

we're talking about it now!!!!

looks like this changed a month ago to use the mapping macros when clownacy coincidently added support for it in clownmaped :thinking: 

it's okay though, I have a branch `asl` that has full macro support and hope to ship it soon

**Comment by FourHawk** [comment]
> looks like this changed a month ago to use the mapping macros when clownacy coincidently added support for it in clownmaped 🤔
> 
Oh right clownmaped can load those files, kinda forgor lmao

> it's okay though, I have a branch `asl` that has full macro support and hope to ship it soon
Oh neat, can't wait for it

**Comment by kirjavascript** [comment]
the version on the `asl` branch is now working if anyone wants to experiment with it

**Comment by FourHawk** [comment]
Once i figure out how to compile that version i'll give it a test

**Comment by kirjavascript** [comment]
available now in 1.3.0
