### ISSUE TITLE
asm68k @ local label error

### ISSUE THREAD

**Issue by VAdaPEGA** [kirjavascript/Flex2#61]
The recent Macro support feature is incompatible with mappings that use asm68k's default local label prefix.

![image](https://github.com/kirjavascript/Flex2/assets/50675500/7f4f8648-887c-4e85-bb05-e30aaa49b63c)

(This isn't too big of a deal for newcomers but it comes off as a huge annoyance for older projects and disassemblies with the default @ local labels)

**Comment by kirjavascript** [comment]
you can use `asm({ basic }) => basic())` to restore the previous behaviour

I'll see if I can just make it support both out of the box though

**Comment by kirjavascript** [comment]
try this https://github.com/kirjavascript/Flex2/releases/tag/1.3.1

**Comment by VAdaPEGA** [comment]
![image](https://github.com/kirjavascript/Flex2/assets/50675500/c5b19f97-6c15-41f1-b993-7a974a09f90a)
still gives an error

**Comment by kirjavascript** [comment]
can you send me the file that's failing?

**Comment by VAdaPEGA** [comment]
`@zed:
@zed_0: 	dc.w @zed_6-@zed
@zed_2: 	dc.w @zed_E-@zed
@zed_4: 	dc.w @zed_16-@zed
@zed_6: 	dc.b $0, $1
	dc.b $FE, $0, $0, $5, $FF, $FF
@zed_E: 	dc.b $0, $1
	dc.b $FC, $0, $0, $4, $FF, $FC
@zed_16: 	dc.b $0, $2
	dc.b $F6, $5, $0, $0, $FF, $F9
	dc.b $0, $0, $0, $6, $0, $A
	even`
nothing too complex, in fact, it was generated by Flex2 in the first place.

**Comment by kirjavascript** [comment]
should be fixed now in 1.3.2. thanks for testing!
