### ISSUE TITLE
Importing from Sprite Sheet doesn't work with DPLCs

### ISSUE THREAD

**Issue by Pacguy64** [kirjavascript/Flex2#7]
Whenever I try to import a sprite sheet while using DPLCs, the art tiles and mappings are generated, but the DPLCs aren't modified properly (which results in scrambled frames). This feature works just fine if DPLCs' are disabled. I'm using uncompressed art and Sonic 2s' format for DPLCs' and mappings, if that's any help.

**Comment by kirjavascript** [comment]
Hey there.

I am unable  to reproduce the issue you're desribing. This issue has never cropped up during development and I certainly tested it a few times.

[Here's a video showing the test.](https://gfycat.com/TanSmoggyHammerkop)

The scrambled frames - are they in Flex 2 or in your ROM? If they are fine in flex 2 but broken in the ROM double check your export settings and try again. If they are scrambled in Flex 2 send me your assets and I will further try to reproduce it.
