### ISSUE TITLE
messed up sprites

### ISSUE THREAD

**Issue by oo1o1o12** [kirjavascript/Flex2#77]
the only normal sprite is the idle for some reason
<img width="211" alt="Screenshot 2024-05-20 at 18 37 03" src="https://github.com/kirjavascript/Flex2/assets/103213250/3b8dbd42-9e5d-4431-81cd-add62b84b0e9">

**Comment by kirjavascript** [comment]
looks like the DPLCs are not correct

you'll need to post more information to allow people to debug it, what are you loading from, etc?

**Comment by oo1o1o12** [comment]
> looks like the DPLCs are not correct
> 
> you'll need to post more information to allow people to debug it, what are you loading from, etc?
 
i fixed it by setting the game format to sonic 2
