### ISSUE TITLE
Support for S&KC mappings/DPLCS

### ISSUE THREAD

**Issue by kirjavascript** [kirjavascript/Flex2#8]
15:58:44 <%MainMemory> snkenjoi: can you add support for S&KC sprite mappings/DPLC, it's the same as S3K but in little endian

**Comment by MainMemory** [comment]
More information: The offset table is always in little endian. For the mappings, the count word is big endian, and the Y offset and size bytes are kept in the same order, the tile index and X offset words are little endian. For the player-type DPLCs, everything is still big endian. I haven't checked the non-player DPLCs, but I wouldn't be surprised if they're the same as the player ones.

**Comment by kirjavascript** [comment]
as discussed on IRC, closing until a split disassembly or other resources are available
