### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by SONIC123CDMANIA** [kirjavascript/Flex2#84]
So, the OG Flex had a web version, but Flex 2 doesn't. Please make a web version.

**Comment by kirjavascript** [comment]
The problem is that it needs access to the filesystem to support project files well

there is further discussion in this thread: https://github.com/kirjavascript/Flex2/issues/82

**Comment by SONIC123CDMANIA** [comment]
Ah, ok.

**Comment by kirjavascript** [comment]
closed in favour of the other thread
