### ISSUE TITLE
Grayscale issue

### ISSUE THREAD

**Issue by Red2010** [kirjavascript/Flex2#85]
While editing the Signpost in my hack I noticed that Flex 2 does not correctly import one of the gray colors in the palette. Instead it replaces them with areas without a background.

Asesprite:
![Captura de pantalla (331)](https://github.com/user-attachments/assets/535952af-417b-4e0c-8290-fca86375eff9)

Flex 2:
![Captura de pantalla (332)](https://github.com/user-attachments/assets/38f8bba1-580f-4a29-96e0-3313c9d24b7d)

**Comment by kirjavascript** [comment]
the top left pixel is used as the transparency pixel when importing

if you add a transparent (or other coloured border) to the image before importing it, it should work

feel free to open another issue if this is still a problem
